"""Unauthenticated, token-protected endpoints — currently just the
invoice PDF download surface used by Zalo bot replies.

Anyone with the link can download the PDF until it expires. The link is
generated by an authorized agent/admin via `get_invoice_pdf_url`; we
verify the HMAC signature here and refuse expired or tampered tokens.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query, Response, status

from app.services import invoice_pdf, invoice_read, orgs as orgs_service
from app.services.pdf_tokens import verify_invoice_pdf_token

router = APIRouter(prefix="/public", tags=["public"])


@router.get("/invoices/{invoice_id}/pdf")
def public_invoice_pdf(
    invoice_id: str,
    t: str = Query(..., description="HMAC token minted by get_invoice_pdf_url"),
) -> Response:
    claims = verify_invoice_pdf_token(t)
    if not claims:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "invalid or expired link")
    if claims["invoice_id"] != invoice_id:
        # Token is signed by us but for a different invoice — refuse.
        # Belt-and-suspenders: prevents a leaked token from being remixed
        # to fetch a sibling invoice in the same org.
        raise HTTPException(status.HTTP_403_FORBIDDEN, "token / invoice mismatch")

    org_id = claims["org_id"]
    inv = invoice_read.get_invoice(org_id, invoice_id)
    if not inv:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "invoice not found")
    org = orgs_service.get_org(org_id)
    if not org:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "org not found")

    pdf_bytes = invoice_pdf.render_invoice_pdf(org, inv)
    filename = f"hoa-don-{invoice_id}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            # `inline` lets mobile browsers preview the PDF in-place; users
            # can then Share → Zalo from the preview. `attachment` would
            # force a download which is awkward inside Zalo's webview.
            "Content-Disposition": f'inline; filename="{filename}"',
            # Don't let intermediaries cache a tokenized URL.
            "Cache-Control": "private, no-store",
        },
    )
